# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "deb/wheezy-amd64"
  config.vm.network "private_network", ip: "192.168.10.16"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../projects", "/projects"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "CodingWithAppsflyer-201501"
    vb.gui = true
    vb.memory = "3072"
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "system"
    chef.add_recipe "rethinkdb"
    chef.add_recipe "nodejs"
    chef.add_recipe "projects" 
  end
end
